# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meteor < Formula
  desc ""
  homepage "https://github.com/stefanlogue/homebrew-tools"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stefanlogue/meteor/releases/download/v0.15.0/meteor-darwin-arm64"
      sha256 "5f7252f3d92a1f15ede675fd310e50311c121fc327761cff57ac444a82e3a3c4"

      def install
        bin.install "meteor-darwin-arm64" => "meteor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stefanlogue/meteor/releases/download/v0.15.0/meteor-darwin-amd64"
      sha256 "37c41f8d2b5315311e7ef9929d35a440fd5050b9d6485a6f2cbfca28185d3fb8"

      def install
        bin.install "meteor-darwin-amd64" => "meteor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stefanlogue/meteor/releases/download/v0.15.0/meteor-linux-amd64"
      sha256 "227aa6e4fa7fdf051de8043a3f4f5ebdd47c6a26315dce5ad38faf8fe490b74f"

      def install
        bin.install "meteor-linux-amd64" => "meteor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanlogue/meteor/releases/download/v0.15.0/meteor-linux-arm64"
      sha256 "02497a316e6e064a554c9f2dc79e4a3c11068884d3d403f41b02a00687e9b7e6"

      def install
        bin.install "meteor-linux-arm64" => "meteor"
      end
    end
  end
end
