# This file was generated by GoReleaser. DO NOT EDIT.
cask "meteor" do
  version "0.31.0"

  on_macos do
    on_intel do
      url "https://github.com/stefanlogue/meteor/releases/download/v#{version}/meteor-darwin-amd64.zip"
      sha256 "1053baa9b04c41fa746c61a5edf1b15bed078814b4254d421eea067488dc6789"
    end
    on_arm do
      url "https://github.com/stefanlogue/meteor/releases/download/v#{version}/meteor-darwin-arm64.zip"
      sha256 "60a910a85ea4d2a734baa62546727b372e3ab292575ee4cd4ce7e82edfd12adf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stefanlogue/meteor/releases/download/v#{version}/meteor-linux-amd64.zip"
      sha256 "5777daa357e5987dbc2d6f2bd0d64d1b908ddcbb7c34deec7401a8c46919417c"
    end
    on_arm do
      url "https://github.com/stefanlogue/meteor/releases/download/v#{version}/meteor-linux-arm64.zip"
      sha256 "c099548092799cb5bb1065d5a78958beaaa8c58d0ce659907566c53246442720"
    end
  end

  name "meteor"
  desc ""
  homepage "https://github.com/stefanlogue/homebrew-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meteor"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/meteor"]
    end
  end

  # No zap stanza required

end
