# This file was generated by GoReleaser. DO NOT EDIT.
cask "meteor" do
  name "meteor"
  desc ""
  homepage "https://github.com/stefanlogue/homebrew-tools"
  version "0.30.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meteor"

  on_macos do
    on_intel do
      url "https://github.com/stefanlogue/meteor/releases/download/v#{version}/meteor-darwin-amd64.zip"
      sha256 "9eda01304943e5e8c47398521d863c917923cff7235002750ff28f8b36021ba3"
    end
    on_arm do
      url "https://github.com/stefanlogue/meteor/releases/download/v#{version}/meteor-darwin-arm64.zip"
      sha256 "4b1a4133604098ddf7255b7614fd3a5808e5e03e1edd8e1def77ea7383bd0318"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stefanlogue/meteor/releases/download/v#{version}/meteor-linux-amd64.zip"
      sha256 "29a06f76c23942ddcb8b6295a942781b8563d8902cd2a0d749a2fa8cdd62b031"
    end
    on_arm do
      url "https://github.com/stefanlogue/meteor/releases/download/v#{version}/meteor-linux-arm64.zip"
      sha256 "5665f81470f696644ee5c9ca43365621c2a21bc11b590e4af07496c7403b6618"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/meteor"]
    end
  end

  # No zap stanza required
end
