# This file was generated by GoReleaser. DO NOT EDIT.
cask "meteor" do
  desc ""
  homepage "https://github.com/stefanlogue/homebrew-tools"
  version "0.28.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meteor"

  on_macos do
    on_intel do
      url "https://github.com/stefanlogue/meteor/releases/download/v0.28.2/meteor-darwin-amd64.zip"
      sha256 "319389f89ba039c48b9d02fff0d7a4952c378dfa6b279fac20bee358d028f13e"
    end
    on_arm do
      url "https://github.com/stefanlogue/meteor/releases/download/v0.28.2/meteor-darwin-arm64.zip"
      sha256 "40b41101394353ba75667298cc71e7212ef769ab537e4a56a890c796ddc1829a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stefanlogue/meteor/releases/download/v0.28.2/meteor-linux-amd64.zip"
      sha256 "9d0b9f65be39ef1fa7fd7b91aca1368d9ce433e87d48728a27fc8c4308a0899a"
    end
    on_arm do
      url "https://github.com/stefanlogue/meteor/releases/download/v0.28.2/meteor-linux-arm64.zip"
      sha256 "974fbd5c8c2dd3f78b335b7f3532febac4642d3a577b61130f5e69b45bdd7054"
    end
  end

  conflicts_with formula: [
      "meteor",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/meteor"]
    end
  end

  # No zap stanza required
end
